### ISSUE TITLE
 Unable to make transfers - index error 

### ISSUE THREAD

**Issue by niall-anthony-mcnulty** [alan-turing-institute/AIrsenal#389]
anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/get_transfer_suggestions.py", line 20, in get_transfer_suggestions
    last_timestamp = all_rows[-1].timestamp
IndexError: list index out of range

**Comment by nbarlowATI** [comment]
Hi @niall-anthony-mcnulty  could you let us know the command you ran, and whether you used the latest version of the code?  (Both "main" and "develop" branches were updated around half an hour ago...)

My guess would be that your FPL team ID didn't get through to the API call - we have been rearranging related functions recently, we might either have missed something, or just fixed it.

**Comment by nbarlowATI** [comment]
In fact I had introduced a bug when running `airsenal_make_transfers` standalone rather than as part of the pipeline, related to passing through the command-line `--fpl_team_id` argument,   This should be fixed now in the `develop` branch.

**Comment by niall-anthony-mcnulty** [comment]
hi @nbarlowATI , thanks for clarifying. The command I used was ' airsenal_make_squad --num_gw 3 '. I'm updating the repo. I'll check again soon and let you know if it's resolved. On a side note, I was curious if there are any resources regarding transfers? For example, If I choose not to use the recommended transfers /or tweak them, will my team be updated in the database? So for example, in the following week, will it give recommendations based on who I have in the team I picked? Or will it pick based on the team suggested for the previous week? Thanks

**Comment by richardthomasdev** [comment]
Can confirm that I see the same error when running `airsenal_run_pipeline`, but I had assumed it was due to the season not starting yet. This happens on `main` and `develop` branches.

> Optimization complete..
Applying suggested transfers...
Traceback (most recent call last):
  File "/Users/richardthomas/opt/anaconda3/envs/airsenalenv/bin/airsenal_make_transfers", line 8, in <module>
    sys.exit(main())
  File "/Users/richardthomas/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/make_transfers.py", line 200, in main
    fpl_team_id
  File "/Users/richardthomas/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/make_transfers.py", line 99, in get_gw_transfer_suggestions
    rows = get_transfer_suggestions(session, TransferSuggestion)
  File "/Users/richardthomas/opt/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/get_transfer_suggestions.py", line 20, in get_transfer_suggestions
    last_timestamp = all_rows[-1].timestamp
IndexError: list index out of range

**Comment by nbarlowATI** [comment]
Hi @richardthomasdev , from the line numbers in the traceback it looks like you're using an older version of the code (we pushed a lot of updates yesterday) - indeed, in the older version the automatic transfers wouldn't work before gw1 as it relied on transfers in/out from the database, rather than querying the API for the current "picks".     Could you try updating to the latest version, redoing `pip install .` and trying again?

@niall-anthony-mcnulty  I think the original error you reported was from the `airsenal_make_transfers` step rather than `airsenal_make_squad` wasn't it?  (the latter will choose a starting squad and put "TransferSuggestions" into the database, but won't actually do the transfers.)
Actually I have just realised that `airsenal_make_transfers` by itself will make the transfers but not set the starting 11 and the captain - also need to run `airsenal_set_lineup` for that.   These should probably be combined into one command because I can't imagine someone would want to do one without the other.   (Note that `airsenal_run_pipeline` does already do both of these).

**Comment by niall-anthony-mcnulty** [comment]
@nbarlowATI Hi, sorry that's right, it was the transfer request. I was wondering if it's possible to tweak the suggested transfers and to update the db accordingly? So the following week it will make recommendations off that team instead of the one suggested? Thanks.

**Comment by richardthomasdev** [comment]
@nbarlowATI I was almost positive I'd pulled the latest changes in! Apologies.

**Comment by nbarlowATI** [comment]
Hi @niall-anthony-mcnulty  sorry, just realised I didn't answer that bit of your question!  :)  
Yep, for future weeks, the recommendations will be based on your actual team, not just off the recommendations it had previously made, so you can always tweak the suggestions if you have a better idea, and it won't stop things working in future gameweeks.

The one exception to this is if you've already made transfers in the same gameweek - after week 1, AIrsenal will work from the team that you had at the end of the previous gameweek (though now we know how to get the current "picks" from the API, this is something we could improve when we get a bit of time!)

**Comment by niall-anthony-mcnulty** [comment]
Hi @nbarlowATI , thanks for elaborating. As for the error, I am still getting the same issue when I try and run the transfer function. I re-ran everything an hour ago, so it should be up to date. I assume my TEAM_ID is the number in the URL tab when I checked past points history ( 7 digits ), right? I'll try updating the repo again and see if it works. Is it even necessary to run this function or can I just use the suggestions and manually change my team via the browser? Also, appreciate all the help. It's really cool stuff what you guys have put together. Thanks! :)

**Comment by nbarlowATI** [comment]
Hi @niall-anthony-mcnulty yes, that's right, that's the easiest way to find your TEAM_ID - it will be some integer between 1 and number-of-people-playing-FPL.
Strange that this still isn't working... Did you redo `pip install . ` after updating the code?   Happy to try and debug this more if you paste a full traceback.
But this step is indeed totally optional - there's nothing to stop you from just making the transfers through the website as normal (this is what we have done all the time up to now).

**Comment by jack89roberts** [comment]
Few ideas for other things you could try:

- There were a few more small changes to `develop` this morning, they're for other problems but worth pulling the latest again just in case.
- If you're using an `FPL_TEAM_ID`  file in the `data` directory make sure it contains only your team ID and nothing else.
- `pip install --force-reinstall .` may help to ensure it's not using any old versions in the background.
-  `airsenal_run_pipeline --clean` will delete and recreate the database, in case anything has gone wrong there.

**Comment by niall-anthony-mcnulty** [comment]
@nbarlowATI pip install . is still necessary if I downloaded it from conda?

**Comment by nbarlowATI** [comment]
@niall-anthony-mcnulty  it's not currently possible to install AIrsenal from conda - the instructions on the README will setup a conda environment that contains all the dependencies of AIrsenal, but to actually install it (i.e. copy the necessary files to your `site-packages` directory), you do need to do 
`pip install .`
from the `AIrsenal/` directory.

Does that make sense?  If you have suggestions for improving the understandability of the README, we'd be very happy to have them! :)

**Comment by niall-anthony-mcnulty** [comment]
@nbarlowATI @jack89roberts  Thank you both! I've managed to get it up and running. Had to pull a few changes, plus deleted and re-did the database. Have a nice day. Cheers.
