### ISSUE TITLE
Error while running pipeline

### ISSUE THREAD

**Issue by mildfuzz** [alan-turing-institute/AIrsenal#697]
CMD:  `airsenal_run_pipeline --weeks_ahead 3 --wildcard_week 24 --apply_transfers`

Run on `develop`

```
....
ATTRIBUTES 2425 Mikel Arteta
Traceback (most recent call last):
  File "/home/john.farrow/miniconda3/envs/airsenalenv/bin/airsenal_run_pipeline", line 8, in <module>
    sys.exit(run_pipeline())
             ^^^^^^^^^^^^^^
  File "/home/john.farrow/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john.farrow/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/john.farrow/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john.farrow/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john.farrow/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/airsenal/scripts/airsenal_run_pipeline.py", line 183, in run_pipeline
    update_ok = update_database(fpl_team_id, update_attr, dbsession)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john.farrow/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/airsenal/scripts/airsenal_run_pipeline.py", line 288, in update_database
    return update_db(season, attr, fpl_team_id, dbsession)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john.farrow/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/airsenal/scripts/update_db.py", line 179, in update_db
    update_attributes(season, session)
  File "/home/john.farrow/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/airsenal/scripts/update_db.py", line 161, in update_attributes
    fill_attributes_table_from_api(
  File "/home/john.farrow/miniconda3/envs/airsenalenv/lib/python3.12/site-packages/airsenal/scripts/fill_player_attributes_table.py", line 113, in fill_attributes_table_from_api
    position = positions[p_summary["element_type"]]
```

**Comment by mildfuzz** [comment]
actually, same thing happens on `master`

**Comment by jack89roberts** [comment]
Oh boy, this must be due to managers being added for the assistant manager chip. We'll need to update the database for it (and quite a lot more to actually implement that chip as an option). I'll have a look as soon as I can but unsure how much work it will be, hopefully not too much to just ignore the managers for now at least.

**Comment by mildfuzz** [comment]
yeah, this is why I left `Arteta` in my copy paste, I suspected that it was related

**Comment by jack89roberts** [comment]
I think if you pull develop now and reinstall it should work (at least as far as the optimisation, I still have it running in the background).

**Comment by jack89roberts** [comment]
Could you pull again, ensure any caches etc. are deleted, and try again? If you open a Python shell in your environment and run these commands your outputs should match the ones commented:

```python
import airsenal
print(airsenal.__version__)  # 1.9.1

from airsenal.mappings import positions
print(positions[5])  # "MNG"
```

**Comment by jack89roberts** [comment]
2nd import should be `from airsenal.framework.mappings import positions`. I've corrected it above.

**Comment by wsandin7** [comment]
After re-pulling and trying again the issue seems to be fixed!

**Comment by wsandin7** [comment]
The only issue I seem to be having right now is that I get squad incomplete after running the optimization. It should however be noted that I've already used my transfers.

**Comment by wsandin7** [comment]
I've tried running some basic commands in a Python shell to see if there's any players in my squad, but it does not appear so. I've removed the database and started from the beginning but that does not seem to fix the issue.

**Comment by jack89roberts** [comment]
Have you set your password and checked it's correct?

**Comment by wsandin7** [comment]
Logging in passes after the second try, so it seems like everything regarding the username and password is correct. The issue arises when trying to fetch the players from my squad with the ID 14385.

**Comment by jack89roberts** [comment]
It does seem to be linked to already having made transfers this GW (I get an error as well). If you scroll up above the error message, you should see the output of the optimization, but it's likely picking up something that's only valid if you hadn't made transfers already. Could you make a separate issue about this?

**Comment by wsandin7** [comment]
Absolutely. I'm away from home right now, but I'll create a separate issue later today when I get back.

**Comment by markajam** [comment]
> Could you pull again, ensure any caches etc. are deleted, and try again? If you open a Python shell in your environment and run these commands your outputs should match the ones commented:
> 
> import airsenal
> print(airsenal.__version__)  # 1.9.1
> 
> from airsenal.framework.mappings import positions
> print(positions[5])  # "MNG"

Likewise. This v1.9.1 clears the error for me and allows the process to run to completion. Not sure if this is just a temporary fix or not. Tks.

**Comment by mildfuzz** [comment]
> I think if you pull develop now and reinstall it should work (at least as far as the optimisation, I still have it running in the background).

when you say reinstall it? do you mean recreate the conda env? or is there a specific command you mean?

**Comment by markajam** [comment]
> when you say reinstall it? do you mean recreate the conda env? or is there a specific command you mean?

John,
I just did this 

```
cd AIrsenal/
git pull
git checkout develop
pip install --force-reinstall .
```

described [here](https://github.com/alan-turing-institute/AIrsenal?tab=readme-ov-file#issues-and-new-features)

**Comment by jack89roberts** [comment]
Thanks @markajam - technically I think git checkout first then git pull is safer, I've updated that in the readme. I've also merged the fix to main now so it's no longer necessary to checkout the develop branch. Deleting and recreating the conda env would also work (if you had pulled develop first).

I'll close this now as I think it's fixed, but we will need to look at implementing the assistant manager chip.

**Comment by mildfuzz** [comment]
Still getting stuck here:

```
Fitting player model for FWD ...
~/miniconda3/envs/airsenalenv/lib/python3.12/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
```
